field_of_view_degrees: 360
goal_point_x: 40
goal_point_y: 5
initial_state_orientation: 1.57
initial_state_velocity: 0
initial_state_x: 70
initial_state_y: -23
max_acceleration: 3.5
max_deceleration: 5
max_velocity: 10
min_resolution: 1
min_shadow_area: 1
min_velocity: 0
planning_horizon: 50
prediction_horizon: 50
reference_speed: 8.3333
scenario_name: DEU_Ffb-1_7_I-1-1
simulation_duration: 300
tracking_enabled: true
vehicle_length: 4.8
vehicle_width: 2
view_range: 100
