#GENERAL
simulation_duration : 50

#EGO_VEHICLE
initial_state_x : 70
initial_state_y : -23
initial_state_orientation: 1.57
initial_state_velocity: 8.3333

vehicle_type : car
vehicle_length : 4.8
vehicle_width : 2
goal_point_x : 40
goal_point_y : 5

#PLANNER
reference_speed : 8.3333
max_acceleration : 3.5
max_deceleration : 5
planning_horizon : 50
safety_margin : 5

#SENSOR
field_of_view_degrees : 360
min_resolution : 1
view_range : 100

#OCCLUSION_TRACKER
min_velocity : 0
max_velocity : 10
min_shadow_area : 1
prediction_horizon : 50
tracking_enabled : True
